### PR TITLE
Portuguese translation for Web3Auth and Openlogin

### PR DESCRIPTION
**Pull request by purybr365**
I just created a new translation based on `pt-BR` using `portuguese` as the language identifier, based on the other identifiers. 

We're building a solution based on Web3Auth at [Picnic](https://usepicnic.com) and it's quite important for us to have 100% of the user interaction on his/her chosen language.

### CODE REVIEW

**Comment by shahbaz17** [comment]
Hey @purybr365 

Thanks for making this PR to include `pt-BR`. 

There were some merge conflicts to this PR, so I have fixed those. Please update the [`Openlogin-locale/locales-login.json`](https://github.com/Web3Auth/web3auth-locales/blob/main/Openlogin-locale/locales-login.json) file to include Portuguese translation.

**Comment by purybr365** [comment]
Hey @shahbaz17,

Just included the missing `locales-login.json` file with Portuguese translation. Can you confirm what will be the language code for me to include in the adapter settings: `pt` or `pt-BR`?

Thanks!
Pedro

**Comment by shahbaz17** [comment]
Hi @purybr365 

Thank you for adding the missing translations. Upon merge and one minor change to the `Web3Auth Modal` package, you'll be able to use the translations using `pt-BR`.

**Review by shahbaz17 — APPROVED** [review]
LGTM, over to @lionellbriones

**Comment by lionellbriones** [comment]
@purybr365 i'm merging this to a feature branch first `feat/pt-test` to test locally first. i'll work on it to be merge to main today

**Review by lionellbriones — APPROVED** [review]
for local testing

**Comment by purybr365** [comment]
Hi there, @lionellbriones ! Do you have any news on the pt-br translation? I'm looking forward to using it when shipping our brand new product.

**Pull request merged**
