### PR TITLE
Add Dutch translations for Web3Auth + Openlogin locale

### PR DESCRIPTION
**Pull request by RickVM**
1. Adds Dutch translations for Openlogin-locale.
2. Also adds translations for "password-requirement-10-char" in locales-wallet-account.json, which seems to be missing for all languages except English

### CODE REVIEW

**Comment by jasperverbeet** [comment]
+1

**Comment by RickVM** [comment]
When can this be integrated? Our app is launching soon, so we need this before the 5th of June :)
@chaitanyapotti

**Comment by shahbaz17** [comment]
Hey @RickVM @jasperverbeet 

I appreciate your effort in adding Dutch language support. However, I noticed that the translations you provided are only for Openlogin-locales. In order to fully integrate this, we require the addition of [Web3Auth-locales](https://github.com/Web3Auth/web3auth-locales/tree/main/Web3Auth-locale) alongside Openlogin-locales.

Would you kindly include these translations as well? Additionally, I have observed some merge conflicts that need your attention.

Thank you.

**Comment by RickVM** [comment]
Hi @shahbaz17 

I've added the translations of Web3Auth-locales. 
For some reason, the formatting of that file is (according to git) different from the files in Openlogin-locale. 
Vscode indicates both use (2) spaces-based indentation. Hence I kept it like that. You can verify the changes by hiding whitespace. 

Please let me know your preference if you want me to change the formatting.

**Comment by shahbaz17** [comment]
Hey @RickVM 

I have rebased this branch with the latest main.

We will do local testing before merging this branch.

**Review by lionellbriones — APPROVED** [review]

**Pull request merged**
